version: "3"
networks:
  selenoidnet:
    external:
      name: selenoidnet # This assumes the network is already created
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    networks:
      selenoidnet: null
    volumes:
      - "$PWD/etc:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/video:/opt/selenoid/video"
      - "$PWD/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "6", "-container-network", "selenoidnet"]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    networks:
      selenoidnet: null
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  test-module:
    image: alekseiabramenko/selenium-test-environment
    environment:
      - HUB_HOST=${HUB_HOST}
      - BROWSER=${BROWSER}
      - HEADLESS=${HEADLESS}
      - VIDEO=${VIDEO}
      - GRID=true
      - SUITE=test-suite.xml
    volumes:
      - ./output/test-results:/usr/share/selenium-tests/target