version: "3"
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: "selenoid"
    network_mode: bridge
    volumes:
      - "$PWD/etc:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/video:/opt/selenoid/video"
      - "$PWD/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "6"]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: "selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  test-module:
    image: alekseiabramenko/selenium-test-environment
    environment:
      - HUB_HOST=172.21.0.1
      - BROWSER=chrome
      - HEADLESS=false
      - VIDEO=true
      - GRID=true
      - SUITE=test-suite.xml
    volumes:
      - ./output/test-results:/usr/share/selenium-tests/target